mathalea.js
lorsqu'on supprimait un exercice dans la liste des exercices il y avait un bug qui empêchait la mise à jour des exercices.
Ajout d'un test pour vérifier que ce qu'on récupère de l'url est cohérent avec la liste des exercices proposés.
+
telechargement de plusieurs fois le même fichier dans mathalealatex si plusieurs exercices.
=> bug suppression exercice

modules/operations.js
Problème signalé dans le cadre du 6C31 des divisions continuaient alors que le reste était nul.
Ajout de l'utilisation de la fonction calcul pour éviter certaines erreurs de calculs avec des décimaux lors de la détermination de la précision.
=> division continue à tort

exercices/6e/6G23-1.js
\thickspace en trop + un symbole degré en double.
=> correction 6G23-1

exercices/4e/4G11.js, mathalea.js, style/style_mathalea.css
A plusieurs reprise je me disais : "mince, cet exercice n'est pas tout a fait ce que je cherchais" alors que c'était prévu dans les paramètres (je ne scrollais pas jusqu'en bas pour ouvrir puis regarder s'il y en avait). Proposition suivante : affichage en tooltip des tooltips prévus pour les champs de paramètres + un icone pour y accéder.
* ne me semble pas trop charger l'affichage 
* permet de voir plus rapidement les options (en particulier les niveaux de difficultés) des exercices.
+ Prise en compte des flèches à supprimer pour le premier et dernier exercice.
=> faciliter l'accès aux paramètres.

src/js/mathalea.js, src/js/modules/dom.js, src/js/modules/messages.js
J'ai ajouté qq fcts pour manipuler le dom, et modifié un peu la façon de gérer les feedback (la fct prend un conteneur et ajoute les éléments dedans plutôt que de construire du html et le retourner, ça évite le couplage lié au id, et les collisions d'id)
=> refacto gestion feedback (plus d'id pour éviter les collisions, et simplifier les listeners)

src/js/exercices/2e/2L13.js, src/js/modules/outils.js
Lorsque `${rienSi1(c)}` était vide et que `${texSymbole(symboleInegalite)}` était `\\leq` ou `\\geq`, le `texSymbole` se mélangeait avec le `x` d'après et donnait par exemple un `\\geqx` ininterprétable.
Le fix consistait à ajouter un espace \*-\*
=> bugfix 2L13 + ESLint outils.js

jsdoc/tutorials/guideInteractifAmc.md, src/js/exercices/CM/CM000.js, src/js/modules/outils.js
Au cas où SetReponse est utilisée mais que propositions n'était pas défini, exportQcmAmc provoquait une erreur en allant chercher une valeur n'éxistant pas pour la correction. Initialement, autoCorrection[i].propositions[0].texte devrait contenir le texte de la correction pour la commande AMC \explain...
=> Bug Fix AMC : 

src/js/mathalea.js, src/js/modules/gestionInteractif.js, src/js/modules/outils.js
En ajoutant l'id de l'exercice concerné par le bouton, on s'assure que le bouton est bien relié à la bonne fonction de vérification (qcm, numerique,...).
Cela ne règle pas le problème des handlers superflus qui s'accumulent.
=> Règle provisoirement le bug des mauvais boutons de validation

src/js/mathalea.js
Dans la vue embed, il n'y a pas la bouton CAN ajout d'un test avant de le mettre à "disabled" quand les exercices ne sont pas interactifs.
J'en ai profité pour corriger le bug signalé sur les filtres
=> Bug bouton can

src/js/mathalea.js, src/js/modules/initDom.js
Par contre je n'ai pas trouvé comment récupérer la hauteur de l'animation IEP.
J'ai calculé qu'elle faisait environ 73% de la largeur et ai donc ajouté 75% de la largeur + 60px (pour le bouton et pour avoir une marge) à la hauteur
=> prévient Anki d'augmenter la taille de l'embed en cas d'animation IEP

src/js/modules/Grandeur.js
Suite remontée bugsnag : si on se trompe de "dimension" sur les unités (cm au lieu de cm² par exemple) une erreur js empêchait la suite de la vérification des réponses.
=> fix: conversion plus robuste

src/js/exercices/6e/_Tables_de_multiplications.js
En mode AMC, quand on changeait le paramètre s2 de 2 (à trou) à 3 (mélange), on avait des réponses attendues qui correspondaient à l'autre facteur voir au résultat quand c'était une question à trou.
un this.autoCorrection = [] en début de this.nouvelleVersion semble régler le problème.
Il se pourrait que nombre d'exercices soient concernés par cette erreur !
Point de vigilance !
=> fix; _Tables_de_multiplications : valeurs résiduelles dans this.autoCorrection

src/js/exercices/1e/1AN14-4.js
Le cas monome2 = \pm 2x^2 laissait traîner un "1x^2"
=> fix: Corrections monome2/racine

src/css/style_mathalea.css, src/js/modules/loaders.js
- Il ne fonctionnait plus hors intégration moodle
- Il laissait un grand espace à la fin de la page lors de son ouverture dans l'intégration moodle
=> Corrige le clavier mathématique

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
L'objectif de cette fonction est de mettre en forme une expression mathématique (numérique ou littérale), une équation ou une inéquation décrite par une chaîne de caractères ascii. Cette chaîne est convertie au format mathjs avant traitement.
La sortie est une chaîne de caractères décrivant l'expression au format LaTex.
Elle repose sur des choix mais certains sont paramétrables :
- a/b deviendra $\dfrac{a}{b}$
- les divisions sont "applaties" : a/b*c/d qui donne $\dfrac{\dfrac{a}{b}\times c}{d}$ avec `'mathjs'` et donne $\dfrac{a}{b}\times \dfrac{c}{d}$ avec `toTex()`.
- $\dfrac{-2}{3}$ est converti en $-\dfrac{2}{3}$
- les parenthèses inutiles sont supprimées
- les 1 ou -1 sont supprimés devant une parenthèse ou une lettre (paramétrable)
- les +0 ou +0*n sont supprimés (paramétrable)
- …
=> feat: fonction toTex() dans outilsMathjs (documentation)

src/js/exercices/beta/betaEquations.js, src/js/exercices/beta/betaModele50_Mathsteps.js, src/js/modules/outilsMathjs.js
- fix : resoudre() corriger le problème de la disparition d'une étape dans le cas particulier ax+b=0
- feat : resoudre() Ajout d'un paramètre pour montrer des étapes masquées
- feat : toTex() Supprimer les parenthèses à la racine du noeud
=> fix: outilsMathjs

src/js/modules/outils.js
texNombre(0) affichait '0 e + 0' dans le 6S11 à la sortie de math.format(0,{notation: 'auto', lowerExp: 0, upperExp: 0, precision: 0})
Solution trouvée : donner 1 chiffre dans la partie entière des nombres dont la valeur absolue est plus petite que 1.
=> fix texNombre

src/js/modules/2d.js
Dans l'export SVG de labelPoint() il y a un oubli pour la prise en charge de la position 'above left' et un oubli de la prise en charge de la position 'center' (par défaut c'était 'above left' qui était sélectionné).
=> fix: labelPoint()

src/js/exercices/4e/4I1-2.js, src/js/mathalea.js, src/js/modules/outils.js
la fonction renderMathInElement en charge d'afficher en html les formules latex digérait très mal les &nbsp introduits par sp() en context.isHtml.
C'est maintenant réglé avec une fonction preProcess.
=> fix: sp() fonctionne maintenant aussi bien en mode math qu'en mode texte.

src/js/modules/outils.js
Ajout de zéros non significatifs (par exemple pour des prix).
texNombre(nb, n) continue de fonctionner en affichant au plus n chiffres après la virgule. (le troisième paramètre est false par défaut).
=> feat: texNombre(nb, n, true) et stringNombre(nb,n,true) force n chiffres après la virgule

src/js/modules/interactif/questionMathLive.js
Un bug se produisait quand l'utilisateur saisissait une lettre ou quelque chose de différent d'un nombre ou d'une fraction.
=> fix: Blindage de QuestionMathLive toutes les fractions.

src/js/modules/FractionEtendue.js, src/js/modules/outils.js
Plus prise en compte dans simplificationDeFractionAvecEtapes() de la suppression des signes au numérateur et au dénominateur quand la fraction est irreductible.
=> feat: FractionX.texSimplificationAvecEtapes

src/js/modules/outils.js
Pour une plus grande précision, il faut ajouter un paramètre : calcul(nombre, 12) par exemple.
=> fix: calcul(nombre) renvoie 6 décimales maxi par défaut

src/assets/m2d/affinite.m2d, src/assets/m2d/transformations_animees.m2d, src/js/modules/2d.js
carreIndirect(A,B) est supprimé car équivalent à carre(B,A)
polygoneRegulierIndirect(A,B,n) supprimé car équivalent à polygoneRegulier(B,A,n)
=> fix: suppression de fonctions inutiles

src/js/exercices/can/3e/can3C13.js, src/js/exercices/can/6e/can6C34.js, src/js/exercices/can/6e/can6M10.js, src/js/exercices/can/6e/can6M11.js, src/js/modules/2d.js, src/js/modules/3d.js, src/js/modules/pyramide.ts
Les pyramides gèrent les fractions maintenant, Pave() ne rendait rien à cause d'un oubli d'ObjetMathalea2d.call(), Boite() accepte maintenant le latex en texteIn, pour peu qu'il commence par $.
=> feat: quelques can et des modifications de Pyramide.ts, 3d.js et 2d.js

src/js/modules/outils.js
contraindreValeur(1, 8, '4', 2) retournait 2, avec cette modification, ça retournerait 4
=> feat: contraindreValeur acceptant les nombres sous forme de string

src/js/exercices/1e/1N11.js, src/js/firstLoaded.js
Fix: window.notify() : c'est pas bien de changer le type d'une variable en cours de fonction...
=> fix: 1N11 utilisait ecritureAlgebrique() et ecritureParentheseSiNegatif() sur des miseEnEvidence() (string)

src/js/modules/2d.js
PolygoneAvecNom() a été modifié pour passer à nommePolygone() un string formaté avec des virgules au cas où les noms aient plus d'un caractère.
=> fix: nommePolygone() n'était pas compatible avec des noms de 2 caractères

src/js/modules/2d.js
Les objets intermédiaires créés dans les objets 2d apparaissent dans l'éditeur (qui stocke la liste de tous les objets) si leur propriété isVisible n'est pas mise à false.
Comme n'apparaissent dans un rendu par la fonction mathalea2d() que les objets finaux que l'on souhaite, cette subtilité a pu passer inaperçu pour nombre d'objets ou de fonctions
=> fix: estSecant() ne laisse plus d'objets intermédiaires dans l'éditeur Mathalea2d

src/js/firstLoaded.js
Mais il faut se pencher sur le comportement de window.notify() en ligne : actuellement, il émet dans la console des messages qui devraient être envoyés à Bugsnag
=> fix; provisoirement je remplace l'alerte par un console.error()
