mathalea/mathalea

include/mathalea2d.js
=> Ajout afficheCoteSegment()

exercices/beta/beta4C25-00.js
Disparition de ListeFraction ?
MAJ
=> beta4C25-00 fonctionnel avec classe Fraction.

modules/outils.js
=> :sparkles: tab_C_L  parametre arraystretch sortie LaTeX de tab_C_L

mathalea.js, style/style_mathalea.css
css involved penser au cache pour voir l'effet ;-)
=> mise en évidence des exercices sélectionnés

exercices/beta/beta6N33-1.js
ajout d'un niveau de difficulté (ajout des % 25, 60 et 90 + possibilité de demander un pourcentage de n'importe quel nombre multiple de 4 < 200) et d'une correction  : 30% de XXX c'est 3 fois 10% de XXX
=> ajout d'un niveau de difficulté dans 6N33-1

exercices/beta/beta6C33-1.js
priorités opératoires, proposition d'exercice (inspiration : https://twitter.com/mathequalslove/status/1373718366100283394).
=> beta 6C33-1

exercices/5e/_Ecrire_une_expression_numerique.js
Quand on changeait de paramètre sur les ex5L10-1 on n'avait plus qu'une seule question.
=> erreur au changement de paramètres dans ex 5L10-1

exercices/6e/6Algo11.js, modules/2d.js
ajout d'une fonction attendre(tempo,lutin) dans 2d.js
ajouts de commentaires JSDOC pour les fonctions du lutin
=> 6Algo11 : le lutin "vibre" quand il note la couleur

exercices/3e/3L13-2.js
nombre de questions bloqué à 2 pour 3L13-2 et exercices hérités
=> ex 3L13-2 nb questions

exercices/beta/beta6C11-1.js
A partir d'une égalité déterminer le quotient et le reste de la division euclidienne
=> division euclidienne beta6C11-1

.gitignore, testsBrowser/helpers/browser.js, testsBrowser/tasks/testAll.js
Avec un peu de factorisation de code, et qq bricoles
=> Aj timeout sur les tests

_private.example/config.js, src/js/bugsnag.js
Dsl, il manquait le plus important, les fichiers concernés
=> aj fichiers oubliés

src/js/exercices/5e/5L13.js, src/js/modules/menuDesExercicesDisponibles.js
Correction du titre du 5L13.
Si titre latex, après sélection la formule apparaissait 2 fois. et si on cliquait sur la formule l'identifiant ajouté était "undefined"
=> Correction lié Latex dans titre.

src/js/exercices/3e/3G30-MG32.js, src/js/exercices/3e/3G30.js, src/js/exercices/3e/3G31-1.js, src/js/exercices/3e/3G31-MG32.js, src/js/exercices/5e/5L14-5.js, src/js/modules/2d.js, src/js/modules/doc/2d.js.html, src/js/modules/fonctionsMaths.js, src/js/modules/outils.js
nouvelles fonctions dans outils.js :
sin(a), cos(a) et tan(a) qui prennent la mesure de l'angle en degrés et retourne le cos, le sin ou la tangente.
ArcTan(x) ArcCos(x) et ArcSin(x) retournent l'angle en degrés.
=> Ajout de fonction trigo en degrés pour Mireille.

package-lock.json, package.json, pnpm-lock.yaml, src/js/mathalea.js, src/js/mathalea_amc.js, src/js/modules/loaders.js, webpack.config.js
Il faudrait régler le pb du build en mode production avant de merger cette branche.
Il faudrait aussi choisir entre loadScript et loadjs (qui font double emploi, j'ai des doutes sur la gestion d'erreur du premier)
=> Fix webpack

src/js/mathalea.js, src/js/modules/mathalea_diaporama.js
On masque les boutons de navigation du diaporama tant qu'ils ne sont pas fonctionnels
=> erreur click sur next avant affichage diaporama

src/js/exercices/1e/1E12.js, src/js/exercices/4e/4L14-0.js, src/js/exercices/5e/5L15.js, src/js/exercices/5e/5N110.js, src/js/exercices/5e/5N14-2.js, src/js/exercices/6e/6C32.js, src/js/exercices/6e/6M20.js, src/js/exercices/6e/6N23.js, src/js/exercices/6e/6N24-1.js, src/js/exercices/6e/6N33-1.js, src/js/exercices/6e/6N33-3.js, src/js/exercices/6e/6N33.js, src/js/exercices/6e/_Exercice_conversions_aires.js, src/js/exercices/6e/_Exercice_conversions_de_longueurs.js
remplacement de Algebrite.eval par calcul
Remarque : restera un seul appel à algebrite dans les exercices : Algebrite.run (pas d'outils pour l'instant) dans le 4C25-0
=> algebrite dans exos

src/js/mathalea.js, src/js/modules/menuDesExercicesDisponibles.js
+ affichage etiquette avec url mathalea.html?ex...
+ affichage icones quand exercices en plein écran.
+ passage en camelCase de fonctions
=> commentaire mathaleajs

src/js/mathalea.js, src/js/modules/2d.js, src/js/modules/3d.js
=> mathalea.truc est remplacé par context.truc

src/js/modules/menuDesExercicesDisponibles.js
Ajout des types des questions AMC dans les menus
=> Menu Générateur AMC

src/js/modules/outils.js
Ça pourrait être mergé tel quel et poursuivi plus tard, mais ça mériterait de continuer à documenter ces fcts, pour permettre aux dev d'exo d'avoir ça dans la doc générée (avec tous les types renseignés, pour les paramètres comme les valeurs de retour, c'est le plus important)
=> début d'ajout de jsdoc (avec simplification du code au passage)

src/js/exercices/6e/6C10-3.js, src/js/modules/outils.js
Oubli d'un } dans le type 1 d'exportQcmAmc, curieux car ça ne faisait buguer a priori que 6C10-3
=> :bug: fix amc 6C10-3 et type 1 dans exportQcmAmc

src/csv/listingParTypes.csv, src/js/exercices/beta/betareperagepave.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
=> Ajout exercice beta repérage

package.json, pnpm-lock.yaml, src/js/exercices/5e/5R20-3.js, src/js/exercices/5e/5R21.js, src/js/exercices/6e/6C10-5.js, src/js/exercices/6e/6C10bis.js, src/js/exercices/6e/6C11.js, src/js/exercices/6e/6G33.js, src/js/exercices/6e/6G41.js, src/js/exercices/6e/6N43-3.js, src/js/exercices/6e/6N43.js
=> AMC niveau 6e vérifié pour la sortie Latex. 

src/html/cm.html, src/js/mathalea.js
il y avait à tort pas de version latex s'il n'y avait pas de consigne + manque la div "erreurcontainer" dans cm.html
=> message_latex_si_pas_de_consigne

src/html/exercice.html, src/js/mathalea.js
* icone paramètre et interactif dans exercice.html
* quand le filtre "interactif" est actif la prévisualisation affichée correspond au mode interactif.
* correction d'une anomalie : perte du mode interactif si on previsualise.
=> icone param et interactif dans exercice.html + preview interactif

src/exosAmcInteractifs.md, src/js/modules/dictionnaireDesExercicesAleatoires.js, tasks/buildDicos.js
ajout d'un compteur au script buildDicos.js
=> :rocket: compétition AMC/INTERACTIF open ! 

pnpm-lock.yaml, src/exosAmcInteractifs.md, src/js/exercices/2e/2L12-2.js, src/js/exercices/2e/2L12-3.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Mise à jour de 2L12-2 : correction détaillée et correction simplifiée disponibles.
Création de 2L12-3 : adaptation de 2L12-2 (dans sa dernière version avec correction détaillée) pour (a-b)^2
=> Matt dev2 l12 2 again

src/js/mathalea.js
Anki fonctionne à nouveau avec ces modifications !
Par contre, je ne savais pas bien où placer le premier `try {` , j'aurais bien aimé le placer juste avant le `if (typeof (window.sessionStorage) === 'object') {` mais je trouvais ça bizarre avec le `else`.
Ce serait peut-être à modifier ?
=> Fix pour les navigateurs n'ayant pas de sessionStorage

src/js/exercices/2e/2G50-2.js, src/js/exercices/2e/2N10-1.js, src/js/exercices/2e/2N24.js
correction d'un petit bug et amélioration correction
=> Amélioration 2G50-2

src/js/exercices/beta/betaExempleXcas2eDegParam.js, src/js/exercices/beta/betaExempleXcasAsymptotes.js, src/js/exercices/beta/betaExempleXcasPolynomes.js
=> Test import

src/js/modules/gestionScores.js
Attention les scripts php lancés pas les appels fecth renvoient du json.
Le message d'erreur en console est normal si on lance un simple pnpm start en local.
Pour utiliser le module de scores en local, il faut un serveur avec php local.
=> Fix gestion scores

src/html/mathalea.html, src/js/modules/dictionnaireDesExercicesAleatoires.js
=> Affiche des barres de défilement lorsque nécessaire + réparation du dictionnaireDesExercicesAleatoires qui était cassé

jsdoc/tutorials/Créer_un_exercice.md
Je pense que c'est beaucoup mieux qu'avant :)
=> Modifications "Créer_un_exercice"

src/js/exercices/2e/2G23.js, src/js/exercices/6e/6M30-0.js, src/js/exercices/6e/6N22.js, src/js/exercices/beta/beta2G22-1.js, src/js/modules/2d.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Exo sur la somme de vecteurs.
l'animation instrumentpoche n'est pas cadrée
=> Essai sur les vecteurs.

src/js/exercices/6e/_Construire_par_symetrie.js
Corrige pour 5G10-1 et toutes les références utilisant ce couteau suisse.
=> Modification énoncé _Construire_pa_symétrie en Latex

src/js/exercices/1e/1E11-3.js
bug valeurs particulières de b=0 et c=0 corrigées
=> amélioration

src/js/mathalea.js, src/js/modules/menuDesExercicesDisponibles.js
J'en ai également profité pour rendre cliquable le mot "interactif" dans le tableau quand on est en mode tableau.
=> icone_interactif cliquable

src/js/exercices/6e/6S10.js, src/js/modules/outils.js
+ révision des modes qcm en sortie AMC
=> Debug 6S10 pour AMC.

src/js/modules/outils.js
Elle retourne la valeur ou l'une des bornes min ou max si ça dépasse d'un côté ou de l'autre. Très utile pour filtrer les paramètres issus des formulaireTexte....
=> Nouvelle fonction contraindreValeur(min,max,valeur)

src/js/modules/outils.js
listeQuestionsToContenuSansNumero(this, false) envoie donc les questions sans ajouter un retour à la ligne entre chaque.
=> Ajout d'un paramètre retourCharriot=true dans la fonction

src/js/exercices/can/4e/can4C05.js
Vu que ce n'est pas demandé dans l'énoncé et qu'on est en 4e.
=> can4C05 accepte des fractions non réduites

src/js/exercices/can/2e/can2C02.js, src/js/exercices/can/2e/can2G01.js, src/js/exercices/can/6e/can6C11.js, src/js/exercices/can/6e/can6C13.js, src/js/exercices/can/6e/can6C14.js, src/js/exercices/can/6e/can6C15.js, src/js/exercices/can/6e/can6C16.js, src/js/exercices/can/6e/can6C17.js, src/js/exercices/can/6e/can6C18.js, src/js/exercices/can/6e/can6C19.js, src/js/exercices/can/6e/can6C20.js, src/js/exercices/can/6e/can6C21.js, src/js/exercices/can/6e/can6C22.js
Améliorations des CAN 6ième jusqu'à la question 6C22.
=> Gilles-CAN6-02

src/js/exercices/can/6e/can6C23.js, src/js/exercices/can/6e/can6C24.js, src/js/exercices/can/6e/can6D01.js, src/js/exercices/can/6e/can6D02.js, src/js/exercices/can/6e/can6D03.js, src/js/exercices/can/6e/can6M01.js, src/js/exercices/can/6e/can6M02.js, src/js/exercices/can/6e/can6M03.js, src/js/exercices/can/6e/can6M04.js, src/js/exercices/can/6e/can6M05.js, src/js/exercices/can/6e/can6M06.js, src/js/exercices/can/6e/can6M07.js, src/js/exercices/can/6e/can6M08.js
amélioration des corrigés de quelques questions CAN 6ième
=> Gilles-CAN6-03

src/js/exercices/can/6e/can6C02.js, src/js/exercices/can/6e/can6C03.js, src/js/exercices/can/6e/can6C04.js, src/js/exercices/can/6e/can6C05.js, src/js/exercices/can/6e/can6C06.js, src/js/exercices/can/6e/can6C07.js, src/js/exercices/can/6e/can6C08.js, src/js/exercices/can/6e/can6C09.js, src/js/exercices/can/6e/can6C10.js, src/js/exercices/can/6e/can6C11.js, src/js/exercices/can/6e/can6C12.js, src/js/exercices/can/6e/can6C13.js, src/js/exercices/can/6e/can6C14.js, src/js/exercices/can/6e/can6C24.js, src/js/exercices/can/6e/can6D01.js, src/js/exercices/can/6e/can6N01.js, src/js/exercices/can/6e/can6N02.js, src/js/exercices/can/6e/can6N03.js, src/js/exercices/can/6e/can6N04.js, src/js/exercices/can/6e/can6N05.js, src/js/exercices/can/6e/can6N06.js, src/js/exercices/can/6e/can6P01.js, src/js/exercices/can/6e/can6P02.js, src/js/exercices/can/6e/can6P03.js, src/js/exercices/can/6e/can6P04.js, src/js/exercices/can/6e/can6S01.js
=> Gilles-CAN6-04

src/js/exercices/can/5e/can5C01.js, src/js/exercices/can/5e/can5C02.js, src/js/exercices/can/5e/can5C03.js, src/js/exercices/can/5e/can5C04.js, src/js/exercices/can/5e/can5C05.js, src/js/exercices/can/5e/can5C06.js, src/js/exercices/can/5e/can5C07.js, src/js/exercices/can/5e/can5C08.js, src/js/exercices/can/5e/can5C11.js, src/js/exercices/can/5e/can5C12.js, src/js/exercices/can/5e/can5C13.js, src/js/exercices/can/5e/can5C14.js, src/js/exercices/can/5e/can5C15.js
Amélioration des CAN5ième jusqu'à CAN5C14
=> Gilles-CAN5-01

src/js/exercices/4e/4G20-2.js, src/js/exercices/6e/6C10-4.js, src/js/exercices/6e/6C20.js, src/js/exercices/6e/6C30-1.js, src/js/exercices/6e/6C30-2.js, src/js/exercices/6e/6C31.js
Correction du Bug relevé par Eric Elter.
=> Ces 6 exos redéfinissaient la valeur de réponse en valeur au lieu de [valeur]

src/js/exercices/can/4e/can4C01.js, src/js/exercices/can/4e/can4C02.js, src/js/exercices/can/4e/can4C03.js, src/js/exercices/can/6e/can6D01.js
Modif CAN6D01 pour le non interactif et améliorations des exercices CAN4C01, CAN4C02 et CAN4C03
=> Gilles-CAN4-01

src/js/exercices/can/4e/can4C04.js, src/js/exercices/can/4e/can4C05.js, src/js/exercices/can/4e/can4C06.js, src/js/exercices/can/4e/can4C07.js, src/js/exercices/can/4e/can4C08.js, src/js/exercices/can/4e/can4C09.js, src/js/exercices/can/4e/can4G01.js, src/js/exercices/can/4e/can4G03.js, src/js/exercices/can/4e/can4G04.js
Modification des corrigés de CAN4ième et améliorations des énoncés. Pour les détails voir le tableau sur slack "CAN"
=> Gilles-CAN4-02

src/js/exercices/can/3e/can3C01.js, src/js/exercices/can/3e/can3C02.js, src/js/exercices/can/3e/can3C03.js, src/js/exercices/can/3e/can3C04.js, src/js/exercices/can/3e/can3C05.js, src/js/exercices/can/3e/can3C06.js, src/js/exercices/can/3e/can3C07.js, src/js/exercices/can/3e/can3E01.js, src/js/exercices/can/3e/can3F01.js, src/js/exercices/can/3e/can3G01.js, src/js/exercices/can/3e/can3G03.js, src/js/exercices/can/3e/can3G04.js, src/js/exercices/can/3e/can3G05.js, src/js/exercices/can/3e/can3L01.js
Amélioration des CAN3ième (détail sur tableau slack "course aux nombres")
=> Gilles-CAN3-01

jsdoc/tutorials/Rendre_un_exercice_exportable_AMC.md, jsdoc/tutorials/Rendre_un_exercice_interactif.md, src/js/exercices/4e/4C21.js, src/js/modules/outils.js
Docs et fichiers outils modifiés
=> feat : AMC hybride, AMCNum comme AMC automtatisé pour fract. et puissan.

src/js/modules/operations.js
Ajout des retenues pour la soustraction et des points pour la multiplication
=> fix: operations.js sortie LaTeX

jsdoc/tutorials/Rendre_un_exercice_interactif.md, src/js/modules/gestionInteractif.js
=> feat : Ajout d'un nouveau formatInteractif : ecritureScientifique

src/js/exercices/6e/6P10.js, src/js/modules/outils.js
Et modification de la fonction pgcd() pour qu'elle accepte plus de deux arguments.
=> fix: 6P10 coquilles corrigées dans la correction

src/js/exercices/can/1e/can1L01.js, src/js/exercices/can/2e/can2G02.js
fix : coquilles CAN1L01 (parenthèses) et can2G02 (titre)
=> CoquillesCAN

src/js/exercices/6e/6C30-6.js, src/js/exercices/6e/6C30-7.js
Par combien multiplier (ou diviser) un nombre pour que le chiffre des unités devienne le chiffre des ...
=> ex : Deux nouveaux exercices de 6ème : 6C30-6 et 6C30-7

src/js/exercices/can/1e/can1F01.js, src/js/exercices/can/2e/can2G07.js, src/js/exercices/can/2e/can2G08.js, src/js/exercices/can/2e/can2L02.js, src/js/exercices/can/2e/can2L03.js, src/js/exercices/can/2e/can2L04.js
fix : changement <center> en texteCentre dans les can
=> CAN-center

src/js/exercices/can/5e/can5C15.js, src/js/exercices/can/5e/can5P01.js
Problème symbole pourcent sur pdf
=> CAN-pourcentages

src/js/mathalea.js, src/js/modules/context.js, src/js/modules/gestionVue.js, src/js/modules/initDom.js, src/js/modules/menuDesExercicesDisponibles.js, src/templates/alacarteDroite.html, src/templates/nav.html
Une première étape pour a_la_carte :
- Ergonomie changée pour en créer à la main.
- Fonctionnement précédent conservé pour le lien avec SACoche
- Pas encore de lien vers AMC
=> feat: choix des exercices dans alc

src/js/exercices/6e/6N10-1.js
Le fonctionnement par défaut est le fonctionnement natif.
=> feat : 6N10-1 ajout de niveaux de difficultés (4 paramètres).

src/js/exercices/3e/3F12-3.js, src/js/modules/outils.js
Rectification AMCHybride pour les fractions.
=> fix: 3F12-3 compatible AMC et interactif.

src/js/exercices/5e/5S11.js, src/js/exercices/6e/6S10.js
récupération des constantes pour AMC et interactif. 6S10 ajout des champs interactifs pout this.sup2 = 2
=> fix: 5S11+ 6S10

src/js/exercices/2e/2N51-5.js
Constantes exportées pour AMC commentées en prévision du futur
=> temp: 2N51-5 

src/js/exercices/2e/2N40-6.js, src/js/exercices/2e/2N41-0.js, src/js/exercices/2e/2N41-1.js, src/js/exercices/2e/2N41-2.js, src/js/exercices/2e/2N41-3.js, src/js/modules/dictionnaireLycee.js
=> 2N41 1,2et 3 + 2N40-6

src/js/modules/outils.js
Retour en arrière pour bug en Html hors contexte Katex
=> Outils>texNombre

src/js/exercices/2e/2N31-1.js, src/js/exercices/2e/2N31-2.js, src/js/exercices/2e/2N31-3.js, src/js/exercices/2e/2N31-4.js, src/js/modules/dictionnaireLycee.js
En attente : rendre 4C33-1 ; 4C33-3 et 4C34 interactifs
=> 2N31 sortent du dico lycee

src/js/exercices/can/c3/canc3C01.js
=> coquillecanC3C01

src/js/exercices/5e/5A11-2.js
=> ex: 5A11-2 qui est une variante de 5A11-1

src/js/exercices/beta/beta2N60-X1.js
modéliser par une équation (seconde)
=> exercice seconde 2N50-3 en beta

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/6e/6N23-6.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Valeur décimale d'une fraction
=> new6N23-6 : 

src/js/exercices/3e/3L10-1.js
Affichait parfois x+0 dans la réponse
=> 3L10-1 : Coquille dans l'affichage de la réponse

src/js/exercices/6e/_Construire_par_symetrie.js, src/js/modules/2d.js
Ajout d'un objet vide2d() à mathalea2d()
=> fix: 6G24-1 plus de segments de longueur 0 et plus de médiatrice de point.

src/js/exercices/beta/beta2N60-X2.js
=> ex2N50-4 en beta2N60-X2

src/js/exercices/4e/4C21.js, src/js/exercices/5e/5N20.js, src/js/exercices/6e/6N23-6.js
Rajout de la possibilité de ne pas donner le résultat sous forme simplifiée
=> feat4C21 : 

src/js/exercices/6e/6G25.js, src/js/modules/2d.js
Utilisation dans 6G25 afin de placer les noms des deux droites près des bords de la fenêtre Mathalea2d.
=> feat: Ajout de fonction fixBordures et positionLabelDroite

src/js/exercices/can/3e/can3L03.js
=> fix : reparation pb can3L03+ajout conclusion

src/js/exercices/3e/3L11-4.js
ecritureParentheseSiNegatif(n) oublié pour les nombres négatifs
=> fix:3L11-4

src/js/exercices/6e/6C12-3.js
Donc 30 problèmes différents à données aléatoires où il faut sélectionner les infos utiles (ou inutiles) pour leur résolution.
=> ex : Nouvel exo 6C12-3. 10 problèmes avec 3 quest. différentes possibles

src/js/exercices/2e/2N30-1.js, src/js/exercices/2e/2N30-2.js, src/js/exercices/2e/2N30-3.js, src/js/exercices/2e/2N30-4.js, src/js/exercices/2e/2N30-5.js, src/js/exercices/2e/2N30-6.js, src/js/exercices/2e/2N30-7.js, src/js/modules/dictionnaireLycee.js
=> Les 2N3 sortent du dico lycee

src/js/mathalea.js, src/js/modules/initDom.js
fix de différentes remontées bugsnag :
* sortable is not a function
* gestion de la touche "entree" dans le mode diapo
* erreur au clic sur nouvelle donnée si un exercice n'est pas correct dans l'url
=> fix: remontees bugsnag

src/js/exercices/3e/3G13.js, src/js/modules/2d.js, src/js/modules/outils.js
Nouvelles fonctionnalités :
3G13.js :
- Nouveaux paramétrages  (figure dans l'énoncé)
- Affichage des longueurs sur les figures
- Correctif pour un affichage correct dans le diaporama (zoom)
2d.js :
- Ajout de la fonction texteSurArc()
- Modification de la fonction fixeBordures()
=> feat: 3G13.js & 2d.js (texteSurArc() et fixeBordures())

src/js/modules/outils.js
Traitement différencié pour les nombres et les objets mathjs.js
=> fix: texNum() > outils.js

src/js/exercices/3e/3G13.js, src/js/modules/outils.js
Les figures sont désormais à l'échelle quand c'est possible. Le cas contraire, il y a une indication que l'échelle n'est pas respectée.
Ajout d'un nouveau type de question
=> feat: 3G13

src/js/modules/outils.js
Ajout d'une fonction avec documentation.
=> feat: listeEntiersSommeDonnee()>outils.js

src/js/exercices/beta/beta3S20-1.js
Nouvel exercice sur le calcul avec probabilités mélangeant diagrammes, ratios, fréquences, pourcentages, utilisation de la stabilisation des fréquences.
=> ex: beta3S20-1

src/js/exercices/beta/beta3S20-1.js
Redéfinition de la fonction traceBarre() : ajout de this.bordure
=> fix: beta3S20-1

src/js/exercices/beta/beta3S20-1.js
- Ajout d'un exercice de conversion en pourcentages
- Ajout d'un exercice de simplification de ratios
- Ajout de l'axe des ordonnées pour les diagrammes
- Dans l'exercice sur les fréquences, l'élève doit maintenant calculer la somme des effectifs à partir du diagramme
- Les ratios ne dépassent plus trois parties a:b:c
- Nettoyage partiel du code (il reste encore à faire)
=> feat: beta3S20-1

src/exosAmcInteractifs.md, src/js/exercices/2e/2N50-3.js, src/js/exercices/2e/2N50-4.js, src/js/exercices/can/5e/can5P05.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
=> CanPourcentage

src/js/exercices/can/5e/can5P02.js
Un cas supplémentaire dans can5P02
=> ajout d'un cas dans can5P02

src/js/exercices/6e/6G24-4.js, src/js/modules/2dinteractif.js
On peut maintenant préciser l'opacité des points cliquables lorsqu'ils sont cliqués.
=> feat: 6G24-4 améliorations + gestion de l'opacité pour pointCliquable

src/js/exercices/3e/3G42.js, src/js/exercices/4e/4C22-1.js, src/js/modules/outils.js
correction de quelques coquilles trouvées en passant.
=> fix: texNombrec sans Algebrite, c'est quand même texNombrec.

src/js/exercices/beta/betaEquations.js, src/js/modules/Change.js, src/js/modules/NodeType.js
Série d'exercices progressifs autour de la résolution d'équations.
Nécessite l'installation de https://github.com/fpiou/mathsteps :
pnpm install fpiou/mathsteps
=> ex: betaEquations

src/exosAmcInteractifs.md, src/js/exercices/can/2e/can2F11.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Comparaison d'images avec la fonction carré
=> CanFonctionsRefVariations

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/can/2e/can2G10.js, src/js/exercices/can/2e/can2G11.js, src/js/exercices/can/2e/can2G13.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
modif interactif/non interactif sur can2G10 et 2G11+titre sur can2G13
=> Modifcan2G10et11

src/js/exercices/3e/3G13.js, src/js/exercices/beta/betaEquations.js
Nouveaux exercices sur les programmes de calcul.
- Exprimer le résultat d'un programme de calcul en fonction de x
- Appliquer un programme de calcul à un nombre
- Remonter un programme de calcul
=> feat: betaEquations

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/2e/beta2S12-1.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
=> 2S12-1 changement nom et commentaires

src/js/exercices/3e/3F12-3.js, src/js/modules/outils.js
fix: alsocorrect corrigé dans l'export AMC
=> fix: 3F12-3 ne demande des fractions que si la réponse en est une

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/2e/2F12-1.js, src/js/exercices/2e/2F31-1.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
2 nouveaux exos en seconde 2F12-1 et 2F31-1
=> NouveauxExoSeconde

src/js/exercices/beta/beta5G30-2.js, src/js/modules/outilsMathsteps.js
Exercices sur la reconnaissance d'angles alternes-internes ou correspondants.
=> ex: 5G30-2

src/js/exercices/beta/beta5G30-2.js
Ajout d'un exercice pour montrer que deux droites sont parallèles
=> feat: beta5G30-2

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/2e/2F32-2.js, src/js/exercices/2e/2G21-1.js, src/js/exercices/2e/2G24-1.js, src/js/exercices/2e/2S10-2.js, src/js/exercices/2e/2S12-2.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
modification de certaines ref seconde
=> ModifExoSeconde

src/js/exercices/beta/beta5G30-2.js, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathsteps.js
Nouveau type d'exercices : calculExpression2
Exemples dans betaEquations : s=69 et s=70
=> feat: outilsMathsteps.js

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/beta5G30-2.js, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
La fonction aleaVariables est décrite avec des exemples.
Le fichier outilsMathsteps.js portera le nom de outilsMathjs.js désormais.
Les fichiers beta5G30-2, betaEquations ont été mis à jour.
=> feat: Documentation pour aleaVariables()

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
Modification du nom de la fonction aleaExpressionLitterale qui devient expressionLitterale.
=> feat: Documentation de outilsMathjs

jsdoc/tutorials/Outils_Mathjs.md
=> feat: Outils_Mathjs.md

src/js/mathalea.js
Lors du click sur les flèches les paramètres n'étaient pas conservés. (sera à compléter pour que ça fonctionne également lorsqu'on déplace les étiquettes dans la barre de sélection)
=> fix: conservation param

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
Tuto pour que context.graine soit placé dans une instance de mathjs
=> feat: RandomSeed (Mathjs)

jsdoc/tutorials/Rendre_un_exercice_exportable_AMC.md, src/js/exercices/6e/6N23-3.js, src/js/exercices/6e/6N23-4.js, src/js/exercices/6e/6N31-4.js, src/js/modules/outils.js
Modif aussi de outils.js et MAJ de la doc AMC.
=> fix : Passage à AMC (voire interactif) de 6N31-4, 6N23-3, 6N23-4.

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
Amélioration de la fonction toTex()
=> feat: outilsMathjs

src/js/exercices/4e/4P10-1.js
=> Fix: 4P10-1 stepAxeSecondaire non défini dans certain cas.

src/css/style_mathalea.css, src/js/modules/loaders.js
Fix #1216
(à tester ! Normalement tout fonctionne mais on ne sait jamais j'ai peut être zappé quelque chose, je n'ai plus les idées toutes clair après avoir passé autant de temps à essayer de corriger ce soucis)
=> Corrige les problèmes de positionnement du clavier mathématique dans les iframes

src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
=> fix: outilsMathjs et betaEquations

src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
Correctif : les ConstantNode sont correctement convertit en mathjs
=> fix: outilsMathjs

src/js/modules/Alea2iep.js
=> Correction coquille dans commentaire

src/js/exercices/1e/1AN14-5.js, src/js/modules/fonctionsMaths.js, src/js/modules/outils.js
- Exercice 1AN14-5 : Dérivée de quotient
- Opérations add/multiply pour Polynome
- Fonction prettyTex
=> ex:1AN14-5

src/js/exercices/1e/1AN14-5.js
=> feat:1AN14-5 interactif

jsdoc/tutorials/Outils_Mathjs.md
Correction des liens vers les images de la documentation
=> fix: Outils_Mathjs.md

src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
La fonction aleaVariable() conserve la graine même après un Nouvelle données.
=> fix: outilMathjs

src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
Renvoie l'expression si aucun calcul n'est effectué
=> fix: calculer()

src/js/exercices/1e/1E11-1.js, src/js/exercices/beta/betaEquations.js, src/js/exercices/beta/betaModele50_Mathsteps.js, src/js/modules/outilsMathjs.js
- la fonction tente les calculs exacts avec le format Fraction de Mathjs
- nouveau paramètre pour appliquer texNombre2
- nouveau paramètre pour avoir les valeurs décimales au lieu du format fraction de Mathjs
1E11-1 :
- modification de 1E11-1 pour être compatible avec la nouvelle fonction aleaVariables()
=> feat: aleaVariables()

src/js/modules/Alea2iep.js
Factorisation de la methode zoom de Alea2iep
=> core: factorisation des méthodes zoom

jsdoc/tutorials/Outils_Mathjs.md, src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
- Ajout de la propriété steps (résultat de solveEquation() de Mathsteps)
- Ajout des solutions
=> feat: resoudre()

src/js/exercices/3e/3F10.js, src/js/exercices/4e/4C21.js, src/js/exercices/6e/6N43-3.js, src/js/exercices/6e/6N43.js, src/js/modules/outils.js
Modification de la fonction sommeDesChiffres() qui prend maintenant en argument un nombre et qui retourne un tableau : [valeur de la somme, string de la somme écrite]
=> fix: remplacement de strings par des numbers dans 4C21, 6N43 et 6N43-3

src/js/exercices/beta/betaEquations.js, src/js/modules/outilsMathjs.js
=> feat: calculer()

src/js/exercices/5e/5C12.js, src/js/exercices/5e/5L14-1.js, src/js/exercices/5e/_Ecrire_une_expression_numerique.js
Les calculs on au moins deux opérations.
=> fix: 5L14-1 les expressions littérales ne sont plus simplifiées.

src/js/exercices/6e/6G23-1.js
[Changes reviewed on CodeStream](https://api.codestream.com/r/Yerj-p5Nhzbwtltg/um03K013TCmtMoFVEjy_lw?src=GitHub) by lhotejc on Jan 30, 2022
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> fix: 6G23-1 Pas d'angles négatifs ou décimaux.

src/js/exercices/6e/6G23-1.js, src/js/exercices/6e/6G23.js
Pour les mesures d'angles, des fausses réponses plus 'cohérentes' Pour construire, plus d'angles en position trop verticales (moins de papier).
=> feat: Modifications 6G23 et 6G23-1

src/js/exercices/2e/2G12-1.js
=> réparation bug confusion points

src/assets/fichiers/automultiplechoice.sty
La version d'AMC datait de 2018 !
=> fix: MaJ de automultiplechoice.sty

src/js/modules/2d.js
J'ai renommé des variables dans TraceBarre et ajouté des bordures à l'objet Vide2d() qui devient Vide2d(x=0,y=0)... on peut passer des coordonnées à vide2d() afin de définir ces bordures, sinon, elles sont en 0,0.
=> fix: un problème avec les bordures de Polygone réglé.

src/js/exercices/beta/aleaFigure/GraphicView.js, src/js/exercices/beta/aleaFigure/group.js, src/js/exercices/beta/betaThales.js
Parallelogrammes et homothetie
=> feat: aleaFigure()

src/js/modules/outilsMathjs.js
Possibilité d'avoir les sous-étapes
=> feat: resoudre de outilsMathjs

src/assets/externalJs/moodle.js, src/js/mathalea.js, src/js/modules/initDom.js, src/js/moodle.js, src/templates/mathaleaMoodle.html, webpack.config.js
- Le fichier est généré est désormais au format GIFT au lieu de XML
- Le code javascript n'est plus inclus dans l'export mais inclus dans un fichier distant
- L'inclusion se fait via un custom élément <mathalea-moodle>
- Pratique pour mettre à jour quelque chose sans devoir rééxporter toutes les questions
=> Simplification de l'export moodle

src/js/exercices/3e/3F13.js, src/js/modules/2d.js
extrémités des segments avec 3 décimales au lieu de 2.
=> fix: 3F13 suppression du cas où il n'y a pas de solution

jsdoc/tutorials/Outils_Mathjs.md
Utiliser Mathjs pour limiter les erreurs.
=> feat: les décimaux avec Mathjs dans la documentation

src/js/modules/outilsMathjs.js
"vérifications" pour les inéquations
=> feat: resoudre

src/js/modules/outilsMathjs.js
=> fix: resoudre()

src/js/exercices/6e/6G14.js
=> fix: 6G14 - Affichage de certains noms de droites dans la correction

src/js/exercices/6e/6N21.js
=> fix: 6N21 - oubli de la prise en compte de la sortie LaTeX

src/js/mathalea.js
Si la relecture était configuré pour n'affiche que la réponse mais pas la question, la réponse ne chargeait pas. Ce commit fix ce problème.
=> Fix moodle dans un rare cas de configuration

src/js/exercices/5e/5N14-3.js
Exo à nouveau complètement fonctionnel.
Merci @lhotejc
=> Fix part5 n14 3

src/js/exercices/4e/4C21.js
En option, par défaut la correction reste comme elle était, en ligne
=> 4C21 ajout d'une présentation de la correction en colonnes

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/modules/dictionnaireDesExercicesAleatoires.js, src/js/modules/interactif/isUserIdOk.js
=> fix: msg bugsnag en mode non connecté avec un exo en mode interactif

src/js/exercices/2e/2F10-4.js
rectif erreur cas particuliers p=0 et autres merdouilles
=> MAJ 2F10-4

jsdoc/tutorials/Les_nombres_dans_Mathalea.md
Parait-il que pour mettre en ligne la doc, il faut te prévenir Rémi ? Voilà, c'est fait.
Finalement, le Wiki, c'est bien pratique, on peut corriger de suite.
=> fix: correction d'une coquille dans la doc.

src/js/modules/2d.js
Redéfinitions des fonctions calcul() et arrondi().
Par défaut elle ne font rien.
Mettre debug à true pour debugger le code Latex.
=> feat: 2d.js

src/js/modules/outils.js
=> fix: texNombre

src/js/modules/2d.js
- Fonction ArcPointPointAngle()
- Fonction TexteSurArc()
=> fix: calcul d'intersection de droites

src/js/modules/aleaFigure/GraphicView.d.ts, src/js/modules/aleaFigure/GraphicView.js, src/js/modules/aleaFigure/GraphicView.ts, src/js/modules/aleaFigure/elements.d.ts, src/js/modules/aleaFigure/elements.js, src/js/modules/aleaFigure/elements.ts, src/js/modules/aleaFigure/grandeurs.d.ts, src/js/modules/aleaFigure/grandeurs.js, src/js/modules/aleaFigure/grandeurs.ts, src/js/modules/aleaFigure/outils.d.ts, src/js/modules/aleaFigure/outils.js, src/js/modules/aleaFigure/outils.ts, src/js/modules/aleaFigure/tsconfig.json, src/js/modules/outilsMathjs.js
Correctifs pour éviter les erreurs de la compilation de la documentation.
=> fix: @returns dans les fichiers aleaFigure

src/js/exercices/2e/2F10-3.js
- Séparation de la consigne générale et des questions.
- Suppression de if inutile
- Corection du cadrage
- Légère factorisation du code
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Amélioration du 2F10-3

src/assets/externalJs/moodle.js, src/js/modules/initDom.js
Les + se transformaient en espace par exemple
=> Fix : Encodage de l'url de transfert de données moodle

src/js/mathalea.js, src/js/modules/initDom.js
URLSearchParams.get décode automatiquement les paramètres
=> Fix le fix sur l'encodage d'url

src/js/mathalea.js
Suppression if dans boucle for.
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Optimisation

src/js/modules/gestionUrl.js
Attention peut être dangereux.
A première vu le site continu de fonctionner mais on sait jamais les effets de bords que ce fix pourrait avoir.
=> Fix réellement le problème moodle et améliore la fonction getUrlSearch

src/js/exercices/3e/3L15-1.js, src/js/exercices/beta/beta3S20-1.js, src/js/exercices/beta/beta3s21.js
Passage de x = ...
à
x_i = ...
<sup> Created from VS Code using [CodeStream](https://codestream.com/?utm_source=cs&utm_medium=pr&utm_campaign=github*com)</sup>
=> Ajout des solutions explicites

src/js/exercices/beta/betaTestFraction.js, src/js/modules/FractionEtendue.js
Si un seul argument est passé, on ajoute 1 comme dénominateur et on utilise l'algorithme d'Eric pour déterminer la fraction.
=> fix: le constructeur de FractionX n'est plus gêné par 1/6

src/js/exercices/5e/5A11-1.js, src/js/mathalea.js, src/js/modules/initDom.js
Le bug pourrait se retrouver dans d'autres exercices.
Il est du à la conversion dans miseAJourDuCode des this.supx de chaine de caractères vers number quand ceux-ci sont des nombres.
L'exercice, lui, attendait un texte !
=> Priorité maximale à ce correctif.

src/js/exercices/5e/5L14-4.js
Corrige un bug rendant inopérant 5L14-4 et 4L16.
=> fix: une parenthèse mal placée.

src/js/exercices/beta/betaTestFraction.js, src/js/modules/FractionEtendue.js, src/js/modules/outils.js
Debug plus mise en évidence de la suppression des - en amont par texFractionSR (texFraction avec signes en rouge).
=> fix: simplificationDeFractionAvecEtapes

src/js/modules/2d.js
Ajouts: precisionLabelX = 1 , precisionLabelY = 1, xLabelEcart = 0.5, yLabelEcart = 0.5
=> feat: repere2 retour de latexParCoordonnees + ajouts

src/js/modules/2d.js
Ajout des grands traits pour les multiples de 5°.
Ajout du centre du rapporteur.
=> feat: amélioration du rapporteur

src/js/modules/2d.js
Au programe :
- colorisation de l'arc
- écart entre mesure et arc réglable
- remplissage de l'angle
- possibilité d'avoir le saillant ou le rentrant.
=> feat: afficheMesureAngle gagne un littéral de paramètres supplémentaires

src/js/modules/2d.js
axeXisVisible et axeYisVisible permettent de choisir si on veut enlever un axe.
La fonction exportée donne maintenant la liste de ses paramètres au survol.
=> feat: repere2 gagne deux paramètres supplémentaires

src/js/exercices/6e/6N23-0.js, src/js/modules/outils.js
calcul(nombre) engendre des erreurs sournoises.
=> fix: nombreEnLettres et 6N23-0

src/js/exercices/beta/betaTestRapporteur.js, src/js/modules/2d.js
- precisionAuDegre (1, 5 ou 10) pour supprimer des graduations
- stepGraduation (10, 20, 30, 60 ou 90) pour supprimer éventuellement des valeurs.
=> feat: rapporteur gagne deux paramètres.

src/js/exercices/beta/betaTestRapporteur.js, src/js/modules/2d.js
rayonsVisibles = false permet de retirer les rayons et le cercle central.
=> feat: ajout d'un autre paramètre au rapporteur

src/js/exercices/beta/betaTexNombre.js, src/js/modules/outilsMathjs.js
En ajoutant à l'objet params de la fonction aleaVariables() les valeurs valueOf: true et type: 'decimal', les variables retournées par la fonction seront des instances de Decimal() (decimal.js).
=> feat: Ajout d'une option permettant de fabriquer des Décimaux avec aleaVariables()

src/js/exercices/can/6e/can6C11.js
J'ai fait ça pour une vidéo Tuto...
=> fix: can6C11 au format Decimal.

jsdoc/tutorials/Creer_un_exercice.md, src/js/exercices/1e/1E11-4.js, src/js/exercices/1e/1E11-5.js, src/js/exercices/1e/1E13.js, src/js/exercices/1e/1P10.js
Plein de coquilles de présentation, mais pas que ça dans 1E11-5
=> fix: corrrection de plein de coquilles dans 1E11-5 + suppr calcul()

src/js/exercices/1e/1P10.js
Aléatoire oublié dans une question
=> Coquille énoncé

src/js/modules/operations.js
retenue forcée sur la dernière ligne signe + ajouté
=> fix: multiplication2d() plus de retenue sur les produits partiels

src/js/exercices/beta/betaPol.js, src/js/modules/2d.js
Polygone.aire() retourne l'aire du polygone
Polygone.triangulation() retourne une liste de triangle pavant le polygone
PolygoneATrous.aire() retourne l'aire du polygone à trous
=> feat: Polygone gagne 2 méthodes et PolygoneATrous en gagne une

src/js/exercices/4e/4G10-2.js, src/js/exercices/4e/4P10.js
Correction de coquilles dans 4G10-2 et dans 4P10
=> Guillaume coquilles

package.json, src/assets/gift/.htaccess, src/assets/gift/mathalea.gift.txt, src/templates/mathaleaMoodle.html, tasks/buildMoodleGift.js
- Le fichier gift est généré à chaque mise en prod (c'est rapide) ou via `npm build:gift`, après si tu préfères que ça ne compile pas à chaque mise en prod je te laisse remodifier
- Un lien pour télécharger le fichier gift est disponible en bas de la page Moodle de Mathalea
- Important : j'ai mis un fichier htaccess dans le dossier `assets/gift`, vérifie que ça casse pas tout le site, c'est le seul truc que j'ai pas pu tester, tout le reste marche normalement
=> Ajout de la génération d'un fichier Gift complet du site disponible au téléchargement

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/5e/5A12-2.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
j'ai tenu compte des conseils et changé une fonction perso pour une ligne de code utilisant outils.js
=> Mimeau 5 a12 2 amelioration

src/js/exercices/6e/6C10-7a.js, src/js/exercices/6e/6C10-7b.js, src/js/exercices/beta/betaYohaku.js, src/js/modules/outils.js
=> feat: 2 nouveaux exercices 6C10-7a et 6C10-7b

src/js/exercices/3e/3A10-1.js, src/js/exercices/3e/3A11.js
Correctif 3A11 OK
Pour 3A10 et 3A10-3 je n'ai pas les Warnings signalés par Eric
=> Fix arithm and co

src/js/exercices/6e/6P10.js, src/js/exercices/beta/betaTexNombre.js, src/js/modules/outils.js
avec ou sans paramètre force... tout a été testé
=> fix: texNombre stringNombre fonctionnent correctement pour les nombres <1

src/js/exercices/3e/3G10-1.js, src/js/exercices/5e/5S14.js, src/js/exercices/6e/6S10-1.js
\thickspace ne fonctionne pas en mode math
=> fix: 5S14 problème dans le LateX du tableau

src/js/exercices/6e/6N10-7.js, src/js/exercices/c3/c3N10-1.js
Je pense avoir supprimé les cas posant problème. Mais dans le doute, il y a des sécurités pour sortir des boucles et un window.notify signalera l'anomalie le cas échéant.
=> fix: c3N10-1 et 6N10-7 problème de boucles sans fin.

src/js/exercices/2e/2F32-2.js, src/js/modules/2dinteractif.js, src/js/modules/3d.js
=> fix : 2F32-2 : Ne pas permettre de mettre autant de questions que voulu.

src/js/exercices/2e/2S30-5.js, src/js/exercices/3e/3S21.js, src/js/modules/2d.js, src/js/modules/arbres.js
=> fix : 2S30-5 : Interactif intégral + correction coquilles sur fractions + corrections orthographiques

pnpm-lock.yaml
Nécessite un pnpm install.
Quelques changements dans mathjs, sesajstools...
=> Mise à jour de quelques dépendances pnpm install requis

src/js/exercices/6e/6C10-8.js, src/js/exercices/Profs/P020.js
Il faudra ajouter des phrases et des mots pour rendre l'exo plus aléatoire...
=> Nouvel exo tirés de P020

src/js/exercices/4e/4C10.js, src/js/modules/FractionEtendue.js, src/js/modules/outils.js
ecritureParenthesesSiNegatif() utilise texNombre et fonctionne avec Decimal
produitFraction n'utilise plus mathjs multiply mais retourne une FractionX non simplifiée.
=> feat: 4C10 nouveau +modification dans outils.js et FractionEtendue.js

src/js/exercices/6e/6G44-1.js, src/js/modules/2d.js
=> fix: 6G44-1 cône revisité + factorisation + bordures

src/js/exercices/3e/3I10-1.js, src/js/modules/noteLaCouleur.js, src/js/modules/outils.js
Ajout de [svgnames] pour le package xcolor dans les préambules.
=> fix: Modifications de couleurs en latex

src/js/exercices/5e/5G30-2.js
Amélioration visuel de sortie pdf
=> fix : 5G30-2

src/js/exercices/4e/4C22.js, src/js/modules/FractionEtendue.js
FractionX.texDiviseFraction() hérite aussi de l'ahout
=> fix: 4C22 ajout d'espaces dans les fractions de fractions.

src/js/exercices/6e/6G23-1.js
=> bug: 6G23-1

src/js/exercices/3e/3S21.js, src/js/modules/arbres.js, src/js/modules/outils.js
=> feat: Arbre >changer la position des probas + fonction texteIndice() dans outils.js

src/js/exercices/3e/3A12-0.js
Choix possible en formulaire case à cocher
=> feat: 3A12-0 les roues s'arrêtent quand elles reviennent à leur position de départ.

src/js/exercices/6e/6P12.js, src/js/modules/outils.js
Et ajout de la fonction miseEnCouleur() qui met un texte LateX en couleur sans le mettre en gras
=> Correction de {,} apparentes dans 6P12

src/js/exercices/6e/6N23-6.js
Correctif correction centième et pas millième
=> fix : 6N23-6

src/js/modules/2d.js
prépare au découpage de 2d.js en modules
=> feat: ajout du mot clé export pour les classes de 2d.js

src/js/modules/outils.js
On s'assure que :
- min et max sont entiers sinon on corrige
- listeAEviter est d'un type correct sinon on corrige.
En cas de soucis, on signale à bugsnag avec un handled event
=> feat: blindage de randint

src/js/exercices/HP/HPC102.js
le graphique ne s'affichait pas à tous les coups
=> fixed: bug graphique

src/js/exercices/can/6e/can6I01.js, src/js/modules/2d.js
c'est une boussole pour scratch3
=> feat: Nouvel ObjetMAthalea2d : RoseDesVents

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/HP/HPC103.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Exercice sur les produits matriciels
=> Maxime hpc103

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/Ex/ExC101.js, src/js/modules/dictionnaireDesExercicesAleatoires.js
Exercice sur les produits matriciels niveau lycée
=> ExC101 init

src/js/exercices/6e/6C10-2.js, src/js/exercices/6e/_Tables_de_multiplications.js, src/js/exercices/can/6e/can6C01.js
Une fois propositionQcm(this, i) exécuté, on ne doit pas recommencer car cela mélange les réponses ! (sauf si le booléen ordered est à true...)
=> fix: can6C01 Un seul propositionQcm() pour éviter de multiples brassages

src/js/exercices/3e/3A12-0.js, src/js/modules/2d/engrenage.js
Suppression du console.log() et ajouts de marqueurs de couleurs différentes.
=> fix: suppression du console.log + amélioration.

src/js/exercices/4e/4C37.js, src/js/exercices/can/1e/can1F22.js, src/js/exercices/can/1e/can1S10.js, src/js/exercices/can/2e/can2F03.js, src/js/exercices/can/2e/can2G12.js, src/js/exercices/can/3e/can3L04.js
Problèmes sur can1F22 : des variables sont utilisées sans être initialisées (x1 et x2)
=> fix: pas de renouvellement de Qcm en cas de can.

src/csv/exosNonAmcNonInteractifs.csv, src/exosAmcInteractifs.md, src/exosNonAmcNonInteractifs.md, src/js/exercices/HP/HPC104.js, src/js/modules/dictionnaireDesExercicesAleatoires.js, src/js/modules/outils.js
J'ai ajouté une méthode à la class MatriceCarree dans outils.js pour afficher la matrice
=> Maxime hpc104

src/js/exercices/HP/HPC103.js
Ca plantait avec les matrices 1x1
=> fixed: HPC103 matrices taille 1x1 evitees

src/js/exercices/4e/4G20-6.js, src/js/exercices/4e/4G20.js, src/js/exercices/4e/4G21.js, src/js/modules/outils.js
Ajustement de la place occupée en AMCOpenNum.
=> feat: modifications AMC pour Pythagore & Cie.

package.json, src/js/exercices/3e/3L13-3.js, src/js/exercices/6e/_Roses.js, src/js/modules/outils.js, src/js/modules/outilsMathjs.js
Règle le soucis pour les exos utilisant _Rose.js, mais OutilsMathjs est toujours cassé. De nombreux exos en dépendent...
=> Mise à jout de mathjs en version 11.4 + correctif pour _Rose.js

src/js/exercices/6e/6G44-1.js
La vérification de non doublon était faite trop tard.
=> Corrige une erreur en mode interactif

src/js/exercices/6e/6C11-3.js, src/js/exercices/6e/6C11.js, src/js/modules/interactif/questionMathLive.js
texNombre() introduit des \\, incompatibles avec les réponses à fournir à setReponse (qui doivent être écrit sans formatage !)
=> fix: 6C11, 6C11-3 présence de texNombre() dans setReponse

src/js/exercices/6e/_Roses.js, src/js/exercices/6e/_Yohaku.js, src/js/exercices/beta/betaTestFraction.js, src/js/modules/gestionInteractif.js, src/js/modules/interactif/questionMathLive.js
il semblerait que le chainage conditionnel ne soit pas supporté par builddicos.js...
=> fix: problème avec le chaînage conditionnel ???

src/js/exercices/5e/5A11-1.js, src/js/exercices/6e/6C10-5.js, src/js/exercices/can/1e/can1F16.js, src/js/modules/2d.js
il faut appeler labyrinthe() avec 3 paramètres. Le troisième étant le scale de la tikzPicture nommé scaleFigure dans l'objet passé en argument (valeur par défaut : 1)
=> Ajout d'un paramètre pour passer le scale (tikz)

src/js/exercices/6e/6G14.js, src/js/exercices/6e/6G52.js
@gvalmont voici ma proposition pour les labels des droites. à regarder
=> fix: proposition de position des étiquettes pour les droites

src/js/exercices/1e/1AN14-4.js, src/js/exercices/1e/1AN14-6.js, src/js/exercices/beta/beta_2F_reso_graphiques.js, src/js/modules/2d.js, src/js/modules/fonctionsMaths.js, src/js/modules/outils.js
Pour Stéphane : j'ai du modifier ton exo beta pour mes tests... je pense que tu es gagnant...
=> Amélioration de CatmulRom et Polynome. Exo de Stéphane révisité

src/js/exercices/4e/4G12-1.js, src/js/exercices/4e/4G15.js, src/js/exercices/4e/4P10.js, src/js/exercices/5e/5L14-3.js, src/js/exercices/5e/_Choisir_expression_litterale.js, src/js/exercices/5e/_Ecrire_une_expression_numerique.js, src/js/modules/2d.js, src/js/modules/outils.js
blindage de texteParPoint() pour éviter d'avoir des $$ en latex.
=> fix: 4G15 & 4G12-1 + texteParPoint()

src/js/exercices/2e/2N41-5.js
Correction du bug de la correction sur le cas 3.
=> Matthieu 2 n41 5

src/js/exercices/2e/2N41-7.js
Modification de la correction des cas 1 et 2 (mise en cohérence) et cas 3 : ajout de crochets
=> Matthieu 2 n41 7

src/js/exercices/3e/3L11-1.js, src/js/exercices/3e/3L12-1.js, src/js/exercices/3e/3L12.js
pour quelques exos de calcul litérral
=> feat: Possibilité de présenter les corrections en colonne 

src/js/exercices/3e/3L14-1.js, src/js/exercices/3e/3L14.js
fixe un problème et rend interactif et AMC 3L14-1 (et 3L14)
=> fix: 3L14-1
